
name: CI for Angular

on:
  pull_request:
    branches: [master]

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
         with:
           node-version: "12.20.2"
      - uses: actions/cache@v3
         with:
           path: ~/.npm
           key: ${{runner.os}}-node-${{hashFiles('**/packahe-lock.json')}}
           restore-keys: | 
            ${{runner.os}}-node-
      - name: NPM Install
         run: npm install
      - name: NPM Install Angular
         run: npm install -g @angular/cli@7.3.10 > /dev/null
      - name: Lint
          run: npm run lint
      - name: Format
          run: npm run format
      - name: NPM build Angular Production
         run: npm run build:prod
      - name: Test
         run: npm run test:ci
      - name: Test coverage
         run: npm run test:ci:cov
      - name: Deploy to my EC2 instance
         uses: easingthemes/ssh-deploy@2.1.5
         with: 
            SSH_PRIVATE_KEY: ${{sectets.SSH_PRIVATE_KEY}}
            SOURCE: "dist/angular-cicd-demo/"
            REMOTE_HOST: "ec2-35-154-154-84.ap-south-1.compute.amazonaws.com"
            REMOTE_USER: "ubuntu"
            Target: "/var/www/html/angular-cicd-demo/"



        